### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by Fale**

### CODE REVIEW

**Review by arthepsy — CHANGES_REQUESTED** [review]
Please, include the header line "The MIT License (MIT)" and wrap it the same as in source code or http://choosealicense.com/licenses/mit/

**Comment by Fale** [comment]
Now is exactly like the choosealicense one. Is it ok?

**Review by arthepsy — CHANGES_REQUESTED** [review]
Sorry, not really. First line should be `The MIT License (MIT)`. 

And the text must wrap (with newlines). Currently, those sentences are just big lines. If You look at licence in source code or at URL I provided, You'll see that sentences are wrapped to be of (column) width 80. To ease the pain, just copy/paste the rest after copyright :smiley:

**Comment by Fale** [comment]
Better now?

**Comment by arthepsy** [comment]
Perfect. Thanks!

**Pull request merged**
